var number = [1,2,3];
var numberCopy = [...number];
numberCopy.push(4);
console.log(number + ' and ' + numberCopy);
console.log('************NestedArrsy****************');
var nestedNumber = [[1],[2]];
var nestedNumberCopy = [...nestedNumber];
nestedNumberCopy[0].push(200);
console.log( nestedNumber , nestedNumberCopy);
console.log('************For****************');
var forNestedCopy = [];
for(i=0;i<nestedNumber.length;i++){
    forNestedCopy[i] = nestedNumber[i];
}
console.log( nestedNumber , forNestedCopy);
console.log('*************Map***************');
var Identity = (x) => x;
var copyMap = nestedNumber.map(Identity);
copyMap[1].push(400);
console.log(nestedNumber,copyMap);
console.log('************FilterFxn****************');
console.log([1,2,3].filter((x) => x%2===0));
console.log('************Filter****************');
var filterCopyNumber = nestedNumber.filter(() => true);
filterCopyNumber[0].push(400);
console.log(filterCopyNumber);
console.log('************Reduce****************');
var reduceCopyNumber = nestedNumber.reduce((newArray, element) => {
    newArray.push(element);
    return newArray;    
},[])
console.log(nestedNumber,reduceCopyNumber);
reduceCopyNumber[1].push(600);
console.log(nestedNumber,reduceCopyNumber);
console.log('************Slice****************');
console.log([1,2,3,4,5,6].slice(1,4));
var sliceCopyNumber;
sliceCopyNumber = nestedNumber.slice();
console.log(nestedNumber,sliceCopyNumber);
sliceCopyNumber[1].push(800);
console.log(nestedNumber,sliceCopyNumber);
console.log('************JSON****************');
var strJSON = JSON.stringify(nestedNumber);
var objJSON = JSON.parse(strJSON);
console.log(nestedNumber,objJSON);
objJSON[0].push(800);
console.log(nestedNumber,objJSON);
console.log('************Concat****************');
console.log([1,2,3,4,5].concat(4));
console.log([1,2,3,4,5].concat([8,9]));
var concatCopyNumber = [];
concatCopyNumber = concatCopyNumber.concat(nestedNumber);
console.log(nestedNumber,concatCopyNumber);
concatCopyNumber[1].push(1000);
console.log(nestedNumber,concatCopyNumber);
console.log('************form****************');
var formCopyNumber = Array.from(nestedNumber);
console.log(nestedNumber,formCopyNumber);
formCopyNumber[0].push(1000);
console.log(nestedNumber,formCopyNumber);